name: API Key Check and Email

on:
  push:
    branches:
      - master

jobs:
  check_keys_and_email:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: Install dependencies
      run: npm install # or yarn install, depending on your project

    - name: Iterate over commit history and check for API keys
      id: check_commits
      run: |
        # Define regular expressions for common API key formats
        API_KEY_REGEX="API_KEY=[A-Za-z0-9_\-]+"
        # Add more regex patterns for different API key formats as needed

        # Iterate over each commit in the repository's history
        for commit_hash in $(git rev-list --all); do
            # Get commit message
            commit_message=$(git log --format=%B -n 1 $commit_hash)

            # Inspect changes introduced by the commit
            changed_files=$(git show --pretty="" --name-only $commit_hash)

            # Search for API keys in each changed file
            found_api_key=false
            for file in $changed_files; do
                if grep -qE "$API_KEY_REGEX" "$file"; then
                    echo "Potential API key found in commit: $commit_hash - $commit_message"
                    echo "Affected file: $file"
                    found_api_key=true
                    # Add more detailed output or logging as needed
                fi
            done

            # Check if API key was found in the commit
            if ! $found_api_key; then
                echo "No potential API keys found in commit: $commit_hash - $commit_message"
            fi
        done

    - name: Send Email if no API keys found
      if: steps.check_commits.outputs.no_keys_found == 'true'
      run: |
        # Script to send email containing commit hashes
        # Use GitHub API to fetch repository owner information
        owner_email=$(curl -s -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" https://api.github.com/repos/${{ github.repository }}/owner | jq -r '.email')

        # Check if owner's email is available
        if [ ! -z "$owner_email" ]; then
            echo "No potential API keys found in commit history." | mail -s "No API Keys Found" $owner_email
        else
            echo "Owner's email not available. Unable to send notification."
        fi
